/// Flutter icons OnniHomesIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OnniHomesIcons
///      fonts:
///       - asset: fonts/OnniHomesIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
library;
import 'package:flutter/widgets.dart';

class OnniHomesIcons {
  OnniHomesIcons._();

  static const _kFontFam = 'OnniHomesIcons';
  static const String? _kFontPkg = null;

  static const IconData houseUser = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faWalking = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emotions = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brainFreeze = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meditation = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData social = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile = IconData(0xf118, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollarSign = IconData(0xf155, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walking = IconData(0xf554, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
